/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Marvel vs. Capcom: Clash of Super Heroes)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800106E0u
#define func_800106E0 BootEntry  /* alias */
